source('2. podatki/uvoz.R', encoding = 'UTF-8')
source('2. podatki/Podatki.R', encoding = 'UTF-8')
source('2. podatki/portfolio1.R')
source('2. podatki/portfolio3.R')
source('2. podatki/portfolio7.R')
source('3. baza/auth.R')
source('3. baza/auth_public.R')
source('3. baza/baza.r', encoding = 'UTF-8')